In [6]:
from algorithms.spectral_clustering import *
from utils.preprocessing import get_friendshipnet_data
from utils.utils import *
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
# _, n, edges, _, _, gender_groups, _  = get_friendshipnet_data()       ##receives gender groups
_, n, edges, _, _, _, gender_groups   = get_friendshipnet_data()        #receives class groups

%matplotlib qt
edges = edges.astype(int)



In [ ]:


# clusters = normalizedSC(n, 5, edges)
# clusters = unnormalizedSC(n, 2, edges)

clusters = unnormalizedConSC(n, 3, edges, gender_groups)
# clusters = normalizedConSC(n, 5, edges, gender_groups)

visualize(n, edges, clusters)

In [9]:
# from algorithms.spectral_clustering import *
# from utils.utils import *

def get_sizes(clusters):
    return list(map(lambda x: len(x), clusters))

# if __name__ == "__main__":
# cluster_sizes = [25,25,25,25]

##########################################################
# cluster_sizes = [10, 20, 30, 40]
# edges, clusters_original = genGraph(100, cluster_sizes, 0.9, 0.1)
# etas = [0.25,0.25,0.25,0.25]
# groups = genGroups(100, etas, clusters_original)
##########################################################


no_of_clusters = 3

groups = gender_groups

## unnormalized vanilla SC ##
clusters_vanilla_u = unnormalizedSC(n, no_of_clusters, edges)
cuts_vanilla_u = []
for c in clusters_vanilla_u:
    cuts_vanilla_u.append(get_num_cuts(edges, c))

group_cluster_mat_vanilla_u = get_group_cluster_matrix(clusters_vanilla_u,
                                                        groups)

## normalized vanilla SC ##
clusters_vanilla = normalizedSC(n, no_of_clusters, edges)
cuts_vanilla = []
for c in clusters_vanilla_u:
    cuts_vanilla.append(get_num_cuts(edges, c))

group_cluster_mat_vanilla = get_group_cluster_matrix(clusters_vanilla,
                                                        groups)

## unnormalized cons SC ##
clusters_con_u = unnormalizedConSC(n, no_of_clusters, edges, groups)
cuts_con_u = []

for c in clusters_con_u:
    cuts_con_u.append(get_num_cuts(edges, c))

group_cluster_mat_con_u = get_group_cluster_matrix(clusters_con_u, groups)

## normalized cons SC ##
clusters_con = normalizedConSC(n, no_of_clusters, edges, groups)
cuts_con = []

for c in clusters_con:
    cuts_con.append(get_num_cuts(edges, c))

group_cluster_mat_con = get_group_cluster_matrix(clusters_con, groups)


clusters = normalizedConSC(n, no_of_clusters, edges, groups)
cuts = []


print("\nvanilla unnormalized")
print("clusters: ", get_sizes(clusters_vanilla_u))
print("cuts: ", cuts_vanilla_u)
print("group cluster matrix:\n", group_cluster_mat_vanilla_u)
print("balance ", get_balance(group_cluster_mat_vanilla_u))

print("\nvanilla normalized")
print("clusters: ", get_sizes(clusters_vanilla))
print("cuts: ", cuts_vanilla)
print("group cluster matrix:\n", group_cluster_mat_vanilla)
print("balance ", get_balance(group_cluster_mat_vanilla))

print("\ncons unnormalized")
print("clusters: ", get_sizes(clusters_con_u))
print("cuts: ", cuts_con_u)
print("group cluster matrix:\n", group_cluster_mat_con_u)
print("balance ", get_balance(group_cluster_mat_con_u))

print("\ncons normalized")
print("clusters: ", get_sizes(clusters_con))
print("cuts: ", cuts_con)
print("group cluster matrix:\n", group_cluster_mat_con)
print("balance ", get_balance(group_cluster_mat_con))

# visualize(100, edges, clusters)


vanilla unnormalized
clusters:  [19, 48, 67]
cuts:  [34, 26, 44]
group cluster matrix:
 [[ 0  0  0  0  0  0 17  2  0]
 [ 5 16 26  0  0  0  0  1  0]
 [ 5  3  2  3  7 15  4  7 21]]
balance  [0.        0.        0.0952381]

vanilla normalized
clusters:  [48, 19, 67]
cuts:  [34, 26, 44]
group cluster matrix:
 [[ 5 16 26  0  0  0  0  1  0]
 [ 0  0  0  0  0  0 17  2  0]
 [ 5  3  2  3  7 15  4  7 21]]
balance  [0.        0.        0.0952381]

cons unnormalized
clusters:  [29, 79, 26]
cuts:  [117, 158, 63]
group cluster matrix:
 [[ 3  2  0  1  1  4 12  1  5]
 [ 6 15 26  1  5  7  1  8 10]
 [ 1  2  2  1  1  4  8  1  6]]
balance  [0.         0.03846154 0.125     ]

cons normalized
clusters:  [8, 1, 125]
cuts:  [14, 1, 15]
group cluster matrix:
 [[ 0  0  0  0  0  1  3  0  4]
 [ 0  0  0  0  0  0  0  0  1]
 [10 19 28  3  7 14 18 10 16]]
balance  [0.         0.         0.10714286]
